### ISSUE TITLE
arm64 release

### ISSUE THREAD

**Issue by rhrytskiv** [CrunchyData/postgres-operator-client#34]
Hi, I'm using m1 mac for my work, would be nice if your CLI tool had arm64 release as well.

**Comment by scart88** [comment]
I'm interested in a arm64 version as well, or homebrew. I think it would be much easier to get started.

**Comment by benjaminjb** [comment]
We have just recently released a new version of the client -- it's [0.2.0](https://github.com/CrunchyData/postgres-operator-client/releases/tag/v0.2.0) and it comes with arm64 build assets for [Mac](https://github.com/CrunchyData/postgres-operator-client/releases/download/v0.2.0/kubectl-pgo-darwin-arm64) and [linux](https://github.com/CrunchyData/postgres-operator-client/releases/download/v0.2.0/kubectl-pgo-linux-arm64). 

As an 0.2.0, it may have issues, so please let us know!

(Brew is an interesting idea, but might be out of scope for the moment, let me think on that.)
