### ISSUE TITLE
Which one to follow? /postgres-operator/4.2.2/pgo-client vs /postgres-operator-client/latest

### ISSUE THREAD

**Issue by vit-h** [CrunchyData/postgres-operator-client#66]
Which documentation should I follow for postgres operator client when using latest PGO instructions?

https://access.crunchydata.com/documentation/postgres-operator/4.2.2/pgo-client/
or
https://access.crunchydata.com/documentation/postgres-operator-client/latest/?

I am trying to setup the cluster and client to be able to learn how to manage it on my AKS env.
I was not able to connect client to claster by the first link, but did it with the second link.
Second link client and instruction missing a lot of capabilities I see in the first link.

I am confused.

**Comment by ValClarkson** [comment]
Hi @vit-h 

The first link is compatible with our old v4 postgres operator and the second link is indeed the one you should use and is compatible with v5 postgres operators.  Sorry for any confusion this has caused.  What commands from the v4 postgres operator client would you like to see in the v5 postgres operator client?
