### ISSUE TITLE
Some features request for pgo client

### ISSUE THREAD

**Issue by Eric-zch** [CrunchyData/postgres-operator-client#67]
Hello There,
Thank you for developing pgo client, which simplify our database mainteance work, especially on database backup and restore.
Is it possible to add below features to pgo client?
(1) shutdown a postgrescluster
(2) startup a postgrescluster
(3) restart a postgrescluster
(4) shutdown pgbouncer
(5) startup pgbouncer
(6) restart pgbouncer
(7) PITR restore an existing postgrescluster to a new postgrescluster, hope a user can provide the timestamp to for the PITR.
(8) Paramters change for postgrescluster, such as number of replicas, database parameters, pgbouncer parameters, etc

Thank you!

**Comment by tjmoore4** [comment]
Since we haven't heard back on this issue for some time, I am closing this issue. If you need further assistance, feel free to re-open this issue or ask a question in our [Discord server](https://discord.com/invite/a7vWKG8Ec9).
