### ISSUE TITLE
Restore isn't working via client: kubectl pgo restore my-cluster --repoName repo2 --options '--type=time --target="2023-09-26 00:00:06+00"'

### ISSUE THREAD

**Issue by vit-h** [CrunchyData/postgres-operator-client#68]
Can't do restore via client commands
For me works only via yaml.

Executing in GitBash
$ kubectl pgo restore itfdb -n pgo --repoName repo2 --options '--type=time --target="2023-09-26 00:00:06+00"'
Error: Apply failed with 1 conflict: conflict with "kubectl-annotate" using postgres-operator.crunchydata.com/v1beta1: .metadata.annotations.postgres-operator.crunchydata.com/pgbackrest-restore
Error: exit status 1

Executing in PowerShell

kubectl  pgo restore itfdb -n pgo --repoName repo1 --options '--type=time --target="2023-09-26 00:00:06+00"'
Error: accepts 1 arg(s), received 2
Error: exit status 1
kubectl pgo restore itfdb -n pgo --repoName repo1 --options '--target="2023-09-26 00:00:06+00"'
Error: Apply failed with 1 conflict: conflict with "kubectl-annotate" using postgres-operator.crunchydata.com/v1beta1: .metadata.annotations.postgres-operator.crunchydata.com/pgbackrest-restore
Error: exit status 1
kubectl pgo restore itfdb -n pgo --repoName repo2 --options '--type=time --target="2023-09-26 00:00:06+00"'
Error: accepts 1 arg(s), received 2
Error: exit status 1
kubectl pgo show backup itfdb --repoName="repo2" -n pgo
stanza: db
    status: ok
    cipher: none

    db (prior)
        wal archive min/max (15): 000000010000000000000001/000000010000000000000009

    db (current)
        wal archive min/max (15): 000000010000000800000000/0000002A000000E200000042

        full backup: 20230922-041951F
            timestamp start/stop: 2023-09-22 04:19:51+00 / 2023-09-22 04:24:33+00
            wal start/stop: 0000001D000000CB000000E6 / 0000001D000000CB000000EA
            database size: 67.6MB, database backup size: 67.6MB
            repo2: backup set size: 11.8MB, backup size: 11.8MB

....

AKS
kubectl pgo version
Client Version: v0.3.0
Operator Version: v5.4.2

**Comment by dsessler7** [comment]
@vit-h, you are seeing this issue because you have already done a restore using the "yaml method" and the client cannot overwrite the annotation that triggers the restore. If you clear the annotation and then try again, I believe it will work as expected. We do have something in the backlog for giving the `pgo` client the ability to overwrite that annotation (for both backups and restores).

**Comment by benjaminjb** [comment]
Hello @vit-h, I'm happy to share the news that we recently released v0.4.0 of the client, which includes a `--force-conflicts` flag for the `pgo restore` command: 

If a different user (like `kubectl`) owns the fields, `pgo restore` should now give you that error and a helpful hint to use the `--force-conflicts` flag. If you use the `--force-conflicts` flag, `pgo` will take ownership of those fields.

Please let us know if there's any problem with that or any other feature suggestions you have.
